### ISSUE TITLE
Model estimation: update stop generation models using SEMCOG CVS

### ISSUE THREAD

**Issue by ColSmith76** [SEMCOG/SEMCOG_CVTM#31]
Transferred CVTM stop generation models are currently based on the Ohio GES data. Re-estimate using the SEMCOG CVS data and replace the model objects in the CVTM.

**Comment by ColSmith76** [comment]
@goreaditya this is the next model to work on. I'll add some notes here and would like to discuss. I've copied the original scripts used to develop the models and the current model objects into dev\Estimation\cv_stops

**Comment by goreaditya** [comment]
@ColSmith76 The estimated model can be found [here](https://github.com/SEMCOG/SEMCOG_CVTM/blob/1257aba22cc66dc27c697211ede3d1519d3e0cc1/dev/Estimation/cv_stops/final_models/cv_goods_model.RDS). Just a brief summary on what the scripts contain:
1. Updates to the helping functions to display AIC and BIC which I used as a criteria to select the final model.
2. Updates to the survey processing scripts:
  a. Uses TAZ SE data.
  b. Uses average skims for distance and time between OD pair.
  c. Generate stops counts for goods, services, and intermediate stops.
3. Updates to the Goods models script. Contains a sequence of models (commented out) that I used to get to the final model. I used the AIC criteria to select final model.

**Comment by ColSmith76** [comment]
@goreaditya  for this model, what I'd like to see before we go any further with estimation is descriptive analysis (any you have done so far and additional to do this afternoon) to look at the stops made by each establishment in the CVS sample. Ideally that will tell the story about the types of stops being made each employment category, how the number of stops relates to business type and size, how the distance to stops from the businesses is distributed, how the type of land use in a zone affects the number and types of stops made, etc

In terms of form I'd like you to write a script and save the results as a set of tables (e.g., in a list in an rdata file) and also to make some charts. See dev/Data_Review_CVS.R for the style of chart we've been including in deliverables for this project.

This will be helpful to document the data used for the stop gen models and as a building block for creating calibration targets.

**Comment by goreaditya** [comment]
@ColSmith76 I have pushed my work in the latest commit. I have created some plots that will help us provide some insights on how stops are being made with respect to various features you described above. These plots can be found here [eda plots](https://github.com/SEMCOG/SEMCOG_CVTM/tree/3d372cd0da76429206c98673541489f53d3a9ee2/dev/Estimation/cv_stops/eda_plots).

**Comment by ColSmith76** [comment]
@goreaditya 
- as discussed, updates here are to move to the industry groupings that you developed for the activities model
- then we can test in application and see how the model performs relative to targets before calibration.

**Comment by ColSmith76** [comment]
New goods and service stops models are based on the CVS, and are implemented and working in the application. Ready to move on to calibration so closing this issue.
