### ISSUE TITLE
Model estimation: establishment activities model

### ISSUE THREAD

**Issue by ColSmith76** [SEMCOG/SEMCOG_CVTM#32]
The activities component in the transferred model includes an empirical distribution based on the Ohio GES. Update the empirical distribution using the SEMCOG CVS.

**Comment by ColSmith76** [comment]
@goreaditya some notes on this model:
1. Starting script is here:  SEMCOG_CVTM\dev\Estimation\cv_activities\Estimation_CV_Acitivities.R
I added code to pull in the processed establishments table and the trip table from the Commercial Vehicle Survey.
To identify whether an establishments vehicles make goods trips, service trips, or both, you'll need to look at the stop purposes for the trips made by the vehicles from that establishment.
The establishments table has the correct Semcog model categories already added to it.
2. We should look at this unweighted, but final version should use the establishment weights. Please take a look at the CVS documentation to understand the weighting in the survey data, that is in E:\Projects\Clients\SEMCOG_CVTM\dev\Data_Processed\Survey\Item_1_2017CVS\SEMCOG_CVS_FinalReport_20190319_Final.pdf
(or WRJMDLPPW07).

Check if there are any employment categories with few responses in the survey, we need to make sure sample size is appropriate and that the split between goods, service, and both makes sense for that industry. Any small sample sizes may have skewed results. Please add questions/summaries here

**Comment by goreaditya** [comment]
@ColSmith76 

I have estimated the parameters of underlying distribution of activity classification for both unweighted and weighted samples. But there are some sample size issues that might need some consideration. The following model unemployment categories have small unweighted sample size or have zeros in one of the three activities: e18_pubadm, e11_compmgt, e15_hospit, e07_utility, and e08_infor. I have concerns about 2 of these 5 categories namely: e11_compmgt and e08_infor. Here's the unweighted cross tabulation of these categories:

|Model_EmpCat | Goods| Service| GoodsAndService| Total|
|:------------|-----:|-------:|---------------:|-----:|
|e18_pubadm   |     0|       0|               1|     1|
|e11_compmgt  |     1|       1|               0|     2|
|e15_hospit   |     0|       2|               0|     2|
|e07_utility  |     0|       2|               2|     4|
|e08_infor    |     4|       2|               2|     8|

**Comment by ColSmith76** [comment]
@goreaditya right, those are the types of establishments that don't really operate many commercial vehicles or were not really represented in the sample. Let ,me take a look at how the model deals with businesses in those employment categories, but otherwise things look ok for the rest of the employment categories.

**Comment by JilanChen** [comment]
> @goreaditya some notes on this model:
> 
> 1. Starting script is here:  SEMCOG_CVTM\dev\Estimation\cv_activities\Estimation_CV_Acitivities.R
>    I added code to pull in the processed establishments table and the trip table from the Commercial Vehicle Survey.
>    To identify whether an establishments vehicles make goods trips, service trips, or both, you'll need to look at the stop purposes for the trips made by the vehicles from that establishment.
>    The establishments table has the correct Semcog model categories already added to it.
> 2. We should look at this unweighted, but final version should use the establishment weights. Please take a look at the CVS documentation to understand the weighting in the survey data, that is in E:\Projects\Clients\SEMCOG_CVTM\dev\Data_Processed\Survey\Item_1_2017CVS\SEMCOG_CVS_FinalReport_20190319_Final.pdf
>    (on WRJMDLPPW07).
> 
> Check if there are any employment categories with few responses in the survey, we need to make sure sample size is appropriate and that the split between goods, service, and both makes sense for that industry. Any small sample sizes may have skewed results. Please add questions/summaries here

Do you estimate the establishment activities based on their responses on NUM_VEH activities  or  or based on their surveyed vehicle activities?

**Comment by ColSmith76** [comment]
@goreaditya some next steps on the activities model: -- at the moment we have distributions for each of the 18 categories. Please can you look at the sample sizes and for smaller ones, create groups of similar employment categories? Please have a go at creating these and export some next summaries, as well as a summary of the sample size for each of the 18 categories and then the groups that you create

**Comment by ColSmith76** [comment]
Model_EmpCat | NEst | GoodsStopsTotal | ServiceStopsTotal | GoodsAndServiceStopsTotal
-- | -- | -- | -- | --
e01_nrm | 16 | 150 | 38 | 0
e02_constr | 156 | 214 | 948 | 1023
e03_manuf | 76 | 381 | 68 | 348
e04_whole | 68 | 439 | 142 | 326
e05_retail | 84 | 537 | 101 | 340
e06_trans | 130 | 1131 | 339 | 1042
e07_utility | 4 | 0 | 13 | 43
e08_infor | 7 | 134 | 6 | 4
e09_finan | 12 | 27 | 37 | 46
e10_pstsvc | 34 | 61 | 146 | 103
e11_compmgt | 2 | 3 | 3 | 0
e12_admsvc | 27 | 14 | 211 | 142
e13_edusvc | 12 | 124 | 22 | 45
e14_medfac | 20 | 20 | 367 | 75
e15_hospit | 2 | 0 | 30 | 0
e16_leisure | 20 | 85 | 32 | 21
e17_othsvc | 35 | 105 | 292 | 272

**Comment by ColSmith76** [comment]
Model is finalized with grouped employment categories (8 categories representing groupings of the 18 SEMOG categories. Includes an "other" category that represents the proportion of establishments who did not make a goods or service commercial vehicle trip on the survey day. This version of the model is implemented and tested in the application.
