### ISSUE TITLE
Firm synthesis: firm_sim_scale_employees -- apply to all emp cats?

### ISSUE THREAD

**Issue by ColSmith76** [SEMCOG/SEMCOG_CVTM#42]
in the initial set up of the model, scaling is restricted to just the categories of firm present in the input establishment data. Need to revisit this during estimation -- should more firms be included in the input data? All employment categories?

**Comment by ColSmith76** [comment]
Compare the categories covered by the establishment data with those represented in the CVS data. At least need coverage of those. Others may not be needed since not expected to operate commercial vehicles

**Comment by JilanChen** [comment]
Do we exclude these categories from the firm synthesizer or still synthesize them but not use them to produce any truck activities?

**Comment by ColSmith76** [comment]
@JilanChen these categories are currently excluded from the firm synthesizer as they are not present at all in the establishment data. The TAZ employment (which is used in the stop generation models to attract trucks trips) does include the employment for these categories). I'll add more commentary when we've looked more at the coverage in the CVS data by category and compared

**Comment by ColSmith76** [comment]
With new establishment data we are now covering all employment categories and matching total employment correctly by category

![firmsyn_emp_by_industry](https://user-images.githubusercontent.com/6803731/76530579-4c60ef00-644a-11ea-824d-8ecfd465805e.png)
![firmsyn_emp_by_taz_industry_scatter](https://user-images.githubusercontent.com/6803731/76530580-4cf98580-644a-11ea-91f5-49248995d486.png)
