### ISSUE TITLE
Version 0.1.5 Model Test Comments and Issues

### ISSUE THREAD

**Issue by JilanChen** [SEMCOG/SEMCOG_CVTM#81]
1.  The path to R needs to be changed to the latest R version: set pathtor="C:\Program Files\R\R-4.0.3\bin\x64 
2.  Error in Sample.int and execution halted

**Comment by ColSmith76** [comment]
batch path updated and also the recent changes made as to continue work on issue #40  resolve the error in sample int caused by missing buffer zone SE data in integrated set up
